services:
  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx_container
    ports:
      - 80:80
      - 443:443
      - 81:81
      - 82:82
    volumes:
      - ./nginx/${NGINX_CONF:-nginx.conf}:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - /etc/letsencrypt/live/konektix.eu/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/konektix.eu/privkey.pem:/etc/nginx/certs/privkey.pem
      - web_app:/apps/web-app
    depends_on:
      - iot-data-hub
      - hub-manager
      - web-app
      - pgadmin

  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker_container
    ports:
      - 1883:1883
      - 8883:8883
      - 9002:9001
    user: 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - /etc/letsencrypt/live/konektix.eu/chain.pem:/mosquitto/certs/chain.pem
      - /etc/letsencrypt/live/konektix.eu/cert.pem:/mosquitto/certs/cert.pem
      - /etc/letsencrypt/live/konektix.eu/privkey.pem:/mosquitto/certs/privkey.pem

  keycloak-db:
    image: postgres:17
    container_name: keycloak_db_container
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloakDB
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: keycloak_container
    # ports:
    #   - 8080:8080
    environment:
      KC_HEALTH_ENABLED: true
      JGROUPS_BIND_ADDR: 0.0.0.0
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloakDB
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KC_PROXY: edge
      KC_PROXY_ADDRESS_FORWARDING: true
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM} # required for keycloak realm initialization
      KEYCLOAK_IOT_DATA_HUB_SECRET: ${KEYCLOAK_IOT_DATA_HUB_SECRET} # required for keycloak realm initialization
      KEYCLOAK_HUB_MANAGER_SECRET: ${KEYCLOAK_HUB_MANAGER_SECRET} # required for keycloak realm initialization
    volumes:
      - ./scripts/keycloak-config-init.sh:/keycloak-config-init.sh # required for keycloak realm initialization
    command: ${KEYCLOAK_COMMAND:-start}
    restart: always
    depends_on:
      - keycloak-db
    healthcheck: # check when 8080 port is reserved on the container
      test: cat /proc/net/tcp6 | grep '00000000000000000000000000000000:1F90 00000000000000000000000000000000:0000' || exit 1
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 120s

  iot-data-hub-db:
    extends:
      file: ../iot-data-hub/docker-compose.yml
      service: iot-data-hub-db
    environment:
      TIMESCALEDB_TELEMETRY: off
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_DB: iotDataHubDB
      POSTGRES_USER: ${IOT_DATA_HUB_DB_USER}
      POSTGRES_PASSWORD: ${IOT_DATA_HUB_DB_PASSWORD}
    volumes:
      - iot_data_hub_db_data:/var/lib/postgresql/data

  iot-data-hub:
    extends:
      file: ../iot-data-hub/docker-compose.yml
      service: iot-data-hub
    environment:
      DATABASE_URL: postgresql://${IOT_DATA_HUB_DB_USER}:${IOT_DATA_HUB_DB_PASSWORD}@iot-data-hub-db/iotDataHubDB
      KEYCLOAK_URL: ${VITE_KEYCLOAK_URL:-https://keycloak.konektix.eu/}
      KEYCLOAK_CLIENT: iot-data-hub
      KEYCLOAK_SECRET: ${KEYCLOAK_IOT_DATA_HUB_SECRET}
      KEYCLOAK_REALM: konektix_realm

    depends_on:
      # - iot-data-hub-db
      # - mqtt-broker
      keycloak:
        condition: service_healthy
        

  hub-manager-db:
    extends:
      file: ../hub-manager/docker-compose.yml
      service: hub-manager-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_DB: hubManagerDB
      POSTGRES_USER: ${HUB_MANAGER_DB_USER}
      POSTGRES_PASSWORD: ${HUB_MANAGER_DB_PASSWORD}
    volumes:
      - hub_manager_db_data:/var/lib/postgresql/data

  hub-manager:
    extends:
      file: ../hub-manager/docker-compose.yml
      service: hub-manager
    environment:
      DATABASE_URL: postgresql://${HUB_MANAGER_DB_USER}:${HUB_MANAGER_DB_PASSWORD}@hub-manager-db/hubManagerDB
      KEYCLOAK_URL: ${VITE_KEYCLOAK_URL:-https://keycloak.konektix.eu/}
      KEYCLOAK_CLIENT: hub-manager
      KEYCLOAK_SECRET: ${KEYCLOAK_HUB_MANAGER_SECRET}
      KEYCLOAK_REALM: konektix_realm
    depends_on:
      # - hub-manager-db
      keycloak:
        condition: service_healthy

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - iot-data-hub-db
      - hub-manager-db
    volumes: 
      - pgadmin:/var/lib/pgadmin

  web-app:
    build:
      dockerfile: ../web-app/Dockerfile
      context: ../web-app
    environment:
      VITE_KEYCLOAK_URL: ${VITE_KEYCLOAK_URL:-https://keycloak.konektix.eu/}
      VITE_KEYCLOAK_REALM: konektix_realm
      VITE_KEYCLOAK_CLIENT: client-web-app
    volumes:
      - web_app:/app/dist

volumes:
  iot_data_hub_db_data:
  hub_manager_db_data:
  keycloak_db_data:
  pgadmin:
  web_app:
