name: deploy

on: 
  workflow_dispatch:
    inputs:
      service:
        description: 'Service requesting a deployment'
        required: false
        default: 'warning'
        type: choice
        options:
        - iot-data-hub
        - web-app

jobs:
  main-workflow-job:
    runs-on: ubuntu-latest

    steps: 
      - run: |
          echo "Service requesting a restart: ${SERVICE}"
        env:
          SERVICE: ${{ inputs.service }}

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          # script: whoami
          script: |
            cd ~/apps/k/Cloud
            git pull origin master
            echo "Service requesting a restart: ${SERVICE}"
