name: deploy

on: 
  workflow_dispatch:
    inputs:
      service:
        description: 'Service requesting a deployment'
        required: false
        default: 'warning'
        type: choice
        options:
        - iot-data-hub
        - web-app

jobs:
  deploy-via-ssh:
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~/apps/k/${{ github.event.inputs.service }}
            git status
            cd ~/apps/k/Cloud
            git status
            echo "Service requesting a deployment: ${{ github.event.inputs.service }}"
       
          # script: |
          #   cd ~/apps/k/Cloud
          #   git pull origin main
          #   echo "Service requesting a deployment: ${{ github.event.inputs.service }}"
       
